### PR TITLE
another, better mockup

### PR DESCRIPTION
**Pull request by mel-thomas**
Another fake PR! It was gonna be real, but then I decided it’d be better to do a true mockup before I screw around with things in here too much. It’s here: https://ash-holistic-stag.glitch.me/. And here's the code: https://glitch.com/edit/#!/ash-holistic-stag. Very rough around the edges, and it’s not responsive at all yet, but I have ideas for that, etc. etc.

But basically the deal is: I’ve been trying to get your available-timeslots-as-clickable-cards idea to work. The main issue I was running into is that it’s kinda overwhelming to have all those timeslots visible at once, since we’re dealing with three simultaneous calendars. So I’m using colors to help make them easier to distinguish at a glance. I think I’m pretty happy with it? I wanna refine tho, obvs. Idk, lmk what you think, and I'll close this after.

Screen Shot 2024-05-05 at 5 19 04 PM

### CODE REVIEW

**Comment by jgravois** [comment]
i think this looks great.

> it’s kinda overwhelming to have all those timeslots visible at once, since we’re dealing with three simultaneous calendars

the pickleball court sees _much_ more action in our neighborhood than the other two. if you have concerns about information overload i'm all for giving it more prominence than the other two (or even setting a filter by default).

**Comment by mel-thomas** [comment]
Ooh okay, that's very good info to know. What if on desktop we still show all three but with a checkbox that lets you toggle visibility? Not sure this exact placement is great, but you get the idea:

Screen Shot 2024-05-06 at 3 59 23 PM

And then on mobile, we could just show one court's schedule at a time controllable via dropdown, with pickleball as the default?

Screen Shot 2024-05-06 at 3 56 24 PM

**Comment by jgravois** [comment]
that'd be killer. for the sake of sharing as much code as possible i think displaying all three in one vertical column by default on mobile and giving folks the same option (a checkbox) for hiding there would work just fine too.

**Comment by mel-thomas** [comment]
Yeah now we're cookin' with gas. I'm gonna try to open a real PR tomorrow with some of the layout stuff.

**Pull request closed without merging**
